version: 2

before:
  hooks:
    - go mod tidy

builds:
  # CLI utils
  - id: 'cli'
    main: './cmd/rails-credentials'
    env:
      - 'CGO_ENABLED=0'
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - '-trimpath'
    ldflags:
      - '-s'
      - '-w'
    goos: ['freebsd', 'windows' ,'linux' ,'darwin']
    goarch: ['amd64', '386', 'arm', 'arm64']
    ignore:
      - goos: 'darwin'
        goarch: '386'
      # missing cipher.NewGCMWithRandomNonce
      - goos: 'freebsd'
        goarch: 'arm'
    binary: 'rails-credentials'
  # Tofu provider
  - id: 'provider'
    main: './cmd/terraform-provider-railscred'
    env:
      - 'CGO_ENABLED=0'
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - '-trimpath'
    ldflags:
      - '-s'
      - '-w'
      - '-X main.version={{.Version}}'
      - '-X main.commit={{.Commit}}'
    goos: ['freebsd', 'windows' ,'linux' ,'darwin']
    goarch: ['amd64', '386', 'arm', 'arm64']
    ignore:
      - goos: 'darwin'
        goarch: '386'
      # missing cipher.NewGCMWithRandomNonce
      - goos: 'freebsd'
        goarch: 'arm'
    binary: 'terraform-provider-railscred_v{{ .Version }}'

archives:
  - id: cli
    ids: ['cli']
    formats: ['zip']
    name_template: '{{ .ProjectName }}_cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  - id: provider
    ids: ['provider']
    formats: ['zip']
    name_template: 'terraform-provider-railscred_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      # if you are using this in a GitHub action or some other automated pipeline, you
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true

changelog:
  disable: true
